/**
 * Core domain types for SpacedTask.
 * All date fields are local date strings in YYYY-MM-DD format.
 * Using string dates (not Date objects) guarantees DST safety.
 */

export interface Task {
  id: string;
  title: string;
  /** Local date YYYY-MM-DD when repetition started */
  startDate: string;
  /** 0-based index into INTERVALS array; max 4 */
  repetitionIndex: number;
  /** Local date YYYY-MM-DD when task is next due */
  nextDueDate: string;
  /** Local date YYYY-MM-DD of last completion, or null */
  lastCompletedDate: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Input payload for creating a new task (id/timestamps generated by DB layer) */
export interface CreateTaskInput {
  title: string;
}

/** Payload returned by IPC handlers — always the full Task shape */
export type TaskRow = Task;

/** Typed result envelope returned by every IPC handler */
export interface IpcResult<T> {
  ok: boolean;
  data?: T;
  error?: string;
}

/** The narrow API surface exposed to the renderer via window.electronAPI */
export interface ElectronAPI {
  getTasks: () => Promise<IpcResult<Task[]>>;
  createTask: (input: { title: string }) => Promise<IpcResult<Task>>;
  completeTask: (input: { id: string }) => Promise<IpcResult<Task>>;
  resetTask: (input: { id: string }) => Promise<IpcResult<Task>>;
  deleteTask: (input: { id: string }) => Promise<IpcResult<boolean>>;
  getTodayLocal: () => Promise<IpcResult<string>>;
  /** Only available in development / E2E test mode */
  setMockDate: (input: { date: string | null }) => Promise<IpcResult<string | null>>;
}

/** IPC channel names — single source of truth shared by main and renderer */
export const IPC_CHANNELS = {
  TASKS_GET_ALL: 'tasks:getAll',
  TASKS_CREATE: 'tasks:create',
  TASKS_COMPLETE: 'tasks:complete',
  TASKS_RESET: 'tasks:reset',
  TASKS_DELETE: 'tasks:delete',
  APP_GET_TODAY: 'app:getTodayLocal',
  TEST_SET_MOCK_DATE: '__test__:setMockDate',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
